---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: guestbook-db-credentials
  namespace: demo
spec:
  encryptedData:
    db-password: AgCDSn4P0Fn9f0eqBNNc9Y8fKGgGd7+bbQACkUO/QRQfO2nCEBfXJKU11UhQe8zVPizJtmEHpd3OsOhaUyTAgY2r0Q6aLL530vlResgtytzwnJFcBcEpJTpGGW0akdqYth1oDzeo3yPM1AvnbMHJ2bHuZy+ucW5Km/FqRCp+2QKp/1+SjDsQN3FzS/d2i4qXNkWvi51+kMMfOeC0bgyKSl3QmP4XyzNifIeGDe6LOc02itHJtF+sDw1uVrbplBvQNWwYSQ3yO2EcYQcNRxFAjW0OzqA6U22Pu7jlHyq+A7d/CSpPugb/HNLz8wWu+y95+p3SnDLkZUm6OSYn2CPCDwuTAfH7X45EJOqPBAsa2/+NzvXWZrjGxB7eD48B1RXr9TNsWAj5bAXaNfs0SVaJtd/bNPy/5WFpJWD+RwA9RsKxZeSIYTpL+aonTZhO5GNR9Q8aEhMGycfnzWhIsw0HxTZO5okBfdS3WTlgmTi+6BtMH33PBkCKlL51V5qwJXLn6qRKFscUutOyCzTSK8iHXyb3gF/CGvDwUGaOLLEuWJQ8a91AGWdT/ijv06CdfYmUMfjYraNI1RaFGRdP/4IVphK9Oqacrp7XsuS0s+q1/0+JAKR6G3b0kNBsRCAaxpZ2b1kCMbk4by2J+eTfyoVzcWFSwiqORxt9A+1TRITVNaq4xt4vZJrQjexObpkXSqNuIj3otS2waHkA0HLvx82wkw==
  template:
    metadata:
      creationTimestamp: null
      name: guestbook-db-credentials
      namespace: demo
